# Sensor Configuration
sensor:
  - platform: statistics
    name: outdoor-temperature-min-last24h
    entity_id: sensor.outdoor_temperature
    state_characteristic: value_min
    max_age:
      hours: 24
  - platform: statistics
    name: outdoor-temperature-max-last24h
    entity_id: sensor.outdoor_temperature
    state_characteristic: value_max
    max_age:
      hours: 24
